# hackyeahAPI/docker-compose.override.yml
services:
  django-web:
    env_file:
      - .env
    container_name: django_web_dev
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    environment:
      DEBUG: 1
      DJANGO_LOGLEVEL: DEBUG
    ports:
      - "8000:8080"
    # This command runs migrations and then starts the development server.
    command: >
      sh -c "
        echo 'Waiting for the database to be ready...' &&
        python manage.py migrate &&
        echo 'Setting up admin panel credentials...' &&
        python manage.py shell -c \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='${DJANGO_SUPERUSER_USERNAME}').exists() or User.objects.create_superuser('${DJANGO_SUPERUSER_USERNAME}', '${DJANGO_SUPERUSER_EMAIL}', '${DJANGO_SUPERUSER_PASSWORD}')\" &&
        echo 'Starting development server...' &&
        python manage.py runserver 0.0.0.0:8080
      "